# Generated by Django 2.0.1 on 2018-11-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20181116_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'usuario pode alterar parametro NF-e'), ('ver_dashboard', 'Pode visuzalizar o dashboard'), ('permissao3', 'Permissao 3'))},
        ),
    ]
