# Generated by Django 2.0.1 on 2018-11-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20181105_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Pode deletar clientes'),)},
        ),
    ]
